### ISSUE TITLE
Is this going to see any more love?

### ISSUE THREAD

**Issue by phdoerfler** [r-raymond/nixos-mailserver#1]
the nix files as they are fail to processed. Are you planning to work on this more?

**Comment by r-raymond** [comment]
This repo is the result of a nixos mailserver that I had running on 16.03 for half a year. I was planning to, but have not yet migrated all of my config from the private repo.

I'll try to do that and make it work on Nixos 17.03. Any help is welcome.

**Comment by r-raymond** [comment]
Should now compile and as far as I can tell work. Any bug reports are welcome.
