### ISSUE TITLE
Using ACME without another nginx process

### ISSUE THREAD

**Issue by oscarcarlsson** [r-raymond/nixos-mailserver#127]
#### Nixos Version: 18.03

On my current setup, I have SNM in a container on a server which already have a nginx process running, which includes the necessary bits for managing ACME certificates.

If I'd try to enable ACME certificates in SNM this would clash with the already existing nginx setup, which is too bad. 

If possible, it would be awesome to use an already existing solution for fetching the certificates.

**Comment by r-raymond** [comment]
Hi, can you use certificateScheme = 1, i.e. manually provide the location where the certificates are?

**Comment by oscarcarlsson** [comment]
Oh. I was too impatient to even notice that option, sorry for creating this issue! I was originally hoping to submit a PR with a fix but that didn't happen.
