### ISSUE TITLE
vmail.group defined multiple times

### ISSUE THREAD

**Issue by nico202** [r-raymond/nixos-mailserver#18]
I get:
error: The unique option `users.users.vmail.group' is defined multiple times, in `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/config/users-groups.nix' and `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/config/users-groups.nix'.
(use ‘--show-trace’ to show detailed location information)

**Comment by r-raymond** [comment]
This is the same error that travis CI is producing, I can't reproduce it on my system. See also travis-ci/travis-ci#8483 were I reported the error. You can work around for now, by removing the two lines mentioned in the travis-ci bug report.

Are you on Nixos or use Nix on a different distribution?

**Comment by nico202** [comment]
Didn't know of this report, work-arounded the same way. However, I'm on NixOS.

nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"18.03pre117327.3fe7cddc30" 

nixos-version: 18.03pre117327.3fe7cddc30 (Impala)

**Comment by r-raymond** [comment]
Hmm this is strange. If I leave the lines out on a fresh virtualbox, I get the error that the vmail user does not exist (what I'd expect). Seems as though Nix somehow sets the vmail user without the user doing anything. I'll investigate further.

**Comment by r-raymond** [comment]
Ok, the problem seems to be related to the exact user name "vmail". Maybe you already have such a user on your system? Anyway, I fixed it by renaming the group and user name to "virtualMail". Let me know if that fixes it for you too.

**Comment by r-raymond** [comment]
Nevermind, this is definitely a bug in nixpkgs. If I specify the name "vmail2" it works, with "virtualMail" it seems to fail again...
