### ISSUE TITLE
Version or hash pinning instructions

### ISSUE THREAD

**Issue by jbboehr** [r-raymond/nixos-mailserver#26]
It would be nice to have the ability to include it in the system configuration using hash or at least revision pinning (like every other nix package).

I tried several ways (`mkDerivation`, `fetchFromGithub`, [stage1 nixpkgs](https://gist.github.com/taktoa/4ec8b0cb6d07857400b07a830ad99558)) but always ran into issues, mostly infinite recursion.

At the moment, I'm just using a git checkout in `/etc/nixos`, which is alright but not ideal IMO.

**Comment by eqyiel** [comment]
@jbboehr FYI there's a bit of dicussion about this in another issue https://github.com/r-raymond/nixos-mailserver/issues/13#issuecomment-343301189

**Comment by jbboehr** [comment]
Ah great. It sounds like fetchTarball is going to have hash support in nix 1.12, but the default version is 1.11.

https://github.com/NixOS/nix/issues/1299

**Comment by jbboehr** [comment]
It sounds like the discussion is about pinning a specific nixpkgs version used by this project, however I'm talking about pinning a specific version of this project used by my system configuration.

Using fetchTarball on a tag or specific revision works fine now I think, but the hash is required to ensure the integrity of the data - the commit referenced by a tag can be changed, although most people don't actually do this.

**Comment by r-raymond** [comment]
Ah I see. I find it curious that `fetchTarball` does not have a hash check yet (and really it should also allow to verify the PGP signature). I guess one way is to manually download the package, check it via `gpg` and and then use the local files. Do you thing I should include a description of how to do that in the README?

**Comment by jbboehr** [comment]
> and really it should also allow to verify the PGP signature

I don't think any of the `fetch*` functions include PGP checking. You could download it, check the PGP signature and then get the hash from that.

fetchTarball is different than all of the other fetch functions in that it is a builtin. The other ones all seem to cause infinite recursion due to a circular dependency on the system config.

> Do you thing I should include a description of how to do that in the README?

You could, but the fundamental issue with the `fetchTarball` example is nix downloading a remote resource to be used in the system configuration automatically without any sort of verification that it hasn't been tampered with.

I think I will stick to a git checkout for now - it's better for testing changes anyway.

**Comment by eqyiel** [comment]
@jbboehr one thing you can do is use a git submodule, that way it will be pinned to a specific commit: https://github.com/eqyiel/deployments/tree/master/realms/tomoyo.maher.fyi/lib

**Comment by jbboehr** [comment]
Yep, that's what I'm doing now.

**Comment by eqyiel** [comment]
@jbboehr I had to look at this again recently and found another way, in case you are still interested: https://github.com/eqyiel/node-imapnotify/blob/442d67892f798869e7bd732e82a626b0d6487957/tests/mail-server.nix#L60

You can make a derivation from this git repo and import default.nix from there.

**Comment by r-raymond** [comment]
If you arrived at a satisfying construction, would you mind sharing it (somewhere in the readme)? Thanks!

**Comment by jbboehr** [comment]
It seems to work alright in the configuration in `/etx/nixos` as long as you do it like this (please excuse the non-idiomatic code):

```nix

{ config, pkgs, ... }:

let
    pkgs2 = import <nixpkgs> {};
    nixos-mailserver = (pkgs2.stdenv.mkDerivation rec {
      name = "nixos-mailserver-${version}";
      version = "2.0.1";

      src = pkgs2.fetchFromGitHub {
        owner = "r-raymond";
        repo = "nixos-mailserver";
        rev = "84e394036666e5eac6891041fd02862b802dfcd3";
        sha256 = "0zzs0rhn9vrfvxq25chclvvsc3246x5pl743c9xnkjly0pfpqbjp";
      };

      dontBuild = true;
      preferLocalBuild = true;

      installPhase = ''
        cp -a . $out
      '';
  });
in
{}
```

If you use pkgs, there is infinite recursion. My guess is the presence of dontBuild is what is causing it to work vs what I've tried before.

**Comment by eqyiel** [comment]
@jbboehr you can actually make it more succinct than that:

https://github.com/eqyiel/node-imapnotify/blob/nixos-mailserver-import-test/tests/mail-server.nix#L29-L36

```      
imports = [
  (import ((import <nixpkgs> {}).fetchFromGitHub {
    owner = "r-raymond";
    repo = "nixos-mailserver";
    rev = "refs/tags/v2.0.2"; # or whatever revision
    sha256 = "117w8da5qk1rchdy6lzx3galw1hks4fpdxz6bglv5may44cz1rqf";
  }) { inherit config lib pkgs; })
];
```

You can update the hash using `nix-prefetch-git` (`nix-env -i nix-prefetch-git`, from 
https://github.com/NixOS/nixpkgs/blob/b4a0c011e81989d8c9e93d8874fae3a072aaacec/pkgs/tools/package-management/nix-prefetch-scripts/default.nix#L23)

```
❯ nix-prefetch-git git@github.com:r-raymond/nixos-mailserver.git --rev v2.0.2 # or whatever revision
Initialized empty Git repository in /private/var/folders/jt/qgrx8lp10ylbdlnb93t54r6c0000gn/T/git-checkout-tmp-Ec43p3Xp/nixos-mailserver/.git/
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 29 (delta 7), reused 8 (delta 0), pack-reused 0
Unpacking objects: 100% (29/29), done.
From github.com:r-raymond/nixos-mailserver
 * tag               v2.0.2     -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is 85217621d93567c1159d6ebc166b7375d74b6fd7
path is /nix/store/74xcgdps63gl01f4vjvayxqd9k91wm43-nixos-mailserver
git human-readable version is -- none --
Commit date is 2017-11-26 12:08:07 +0100
hash is 117w8da5qk1rchdy6lzx3galw1hks4fpdxz6bglv5may44cz1rqf
{
  "url": "git@github.com:r-raymond/nixos-mailserver.git",
  "rev": "85217621d93567c1159d6ebc166b7375d74b6fd7",
  "date": "2017-11-26T12:08:07+01:00",
  "sha256": "117w8da5qk1rchdy6lzx3galw1hks4fpdxz6bglv5may44cz1rqf",
  "fetchSubmodules": true
}
```

(just copy the sha256sum)

Does that work for you?
