### ISSUE TITLE
Opening port 80 when using certificateScheme=3

### ISSUE THREAD

**Issue by dotlambda** [r-raymond/nixos-mailserver#42]
I set up a nixos-mailserver with automatic LE certificates. But when I ran `nixos-rebuild`, the `acme-example.org` service failed, because Let's Encrypt wasn't able to connect to my server (timeout).
When I set
```
networking.firewall.allowedTCPPorts = [ 80 ];
```
it works like a charm.

First of all, it took some time to figure this out.Therefore, I think we should automatically open port 80 when using `certificateScheme = 3`.
Second, I don't know if that's possible but it would be nice if the port was only kept open during the certification process, supposed one doesn't open it manually via `networking.firewall`.

**Comment by r-raymond** [comment]
Sry for running into this, it should have been documented better. I'd be kind of uncomfortable though to let port 80 open the whole time for no reason. It seems as if this is something that needs to be fixed upstream, i.e. the ACME certificate obtaining process should temporarily change the firewall.

Do you think mentioning in the docs that one has to temporarily open port 80 is sufficient?

**Comment by r-raymond** [comment]
On the other hand I just noticed that one would have to reopen the port every 3 months for the update. I guess it is best to just open it.

**Comment by dotlambda** [comment]
Well the question is: Do you see any possibility to automatically open and close it again every 3 months?

**Comment by r-raymond** [comment]
I don't but as I said this would need to be integrated upstream, as the
certificate renewal process knows when to open these ports.

Otherwise we could ditch the implemented renewal and do it ourselves, which
sounds tedious.

If anyone is aware of a possibility let me know!
