### ISSUE TITLE
Postfix has wrong hostname

### ISSUE THREAD

**Issue by geistesk** [r-raymond/nixos-mailserver#43]
After setting up a mailserver (_tag v2.0.1_) and setting my FQDN in `mailserver.fqdn`, which is `$hostname.$domain` for me, Postfix was sending mails from `$hostname.localdomain`. Also configuring `services.postfix.hostname = "$hostname.$domain";` solved this issue for me.
However, I think that this extra line of configuration shouldn't be necessary and should be done by this mailserver.

Thanks for all the good work!

**Comment by r-raymond** [comment]
Sorry for the inconvenience! I have no idea how this slipped through the tests. Let me try to reproduce this with the tests. Do you want to to send a patch?

Thanks for trying out SNM!

**Comment by geistesk** [comment]
I haven't patched SNM at all. My current fix was just adding `services.postfix.hostname = "…";` to my `configuration.nix`.
However, I'd write a patch and send you the PR.

**Comment by r-raymond** [comment]
Awesome. I just added a test which makes sure this remains unbroken in the furture
