### ISSUE TITLE
Using getmail with SNM

### ISSUE THREAD

**Issue by dotlambda** [r-raymond/nixos-mailserver#47]
I'm trying to setup getmail so that it fetches mail from some POP3 server, let's suppose Gmail, and delivers it to the IMAP mailbox.
But I'm neither having luck using
```
[destination]
type = MDA_external
path = ${pkgs.dovecot}/libexec/deliver
arguments = ("-e", "-d", "user@example.org")
user = user@example.org
group = virtualMail
```
nor
```
[destination]
type = Maildir
path = /var/vmail/example.org/user/
user = user@example.org
group = virtualMail
```

Does someone have an idea how to configure getmail properly such that mail really gets delivered?
Both above methods don't yield any errors but mail doesn't show up in the INBOX.

**Comment by r-raymond** [comment]
Disclaimer: I don't know getmail and I don't think I completely understand what you want to do. Anyway if you want to inject mails into SNM you can either

1) deliver to the SMTP (Postfix)
2) deliver to Dovecot via LMTP (I think LMTP replaced LDA, I'm not sure if LDA is available).
3) directly write into maildir

If you use 1) the mail will be virus / spam / dkim checked. 2) is probably easier if you do this for multiple email addresses then 3).

It seems you tried 3) in your second example, here the user should be virtualMail also. For the first option see e.g. [(1)](https://www.howtoforge.com/debian_etch_getmail). Have you tries calling dovecot/deliver manually to see if LDA is available?

Good luck

**Comment by dotlambda** [comment]
Thanks for your quick reply, @r-raymond!

Essentially, I have a Gmail account I don't use anymore. But people still send mails to that account. Therefore, I want these mails to appear in my `user@example.org` inbox. I plan to fetch them using getmail.

Regarding 2): Using `lmtp` and `user = virtualMail` doesn't change anything: getmail still says that the emails are dlivered but they never show up in the inbox.

Using 3) with `user = virtualMail` won't work: `/var/vmail/example.org/user/` is owned by `user@example.org`. Therefore getmail complains:

> cannot read contents of directory /var/vmail/example.org/user/ - check permissions and ownership


Option 1) sounds interesting. My only worry is that mail will not arrive due to the queue being full or something like that. I'll keep the mails in Gmail just to be sure.
But I can't find an easy way to deliver a mail to postfix. Ideally it should be as simple as calling Dovecot's
`lmtp -r user@example.org` and writng the mail to stdin.

**Comment by dotlambda** [comment]
Never mind, I found the issue:
```
msgid=unspecified:
```
When sending a new mail with a specified msgid, both 2) and 3) work like a charm.

But to use the preconfigured spam filtering it would be nice to use option 1) after all. If there's no easy way to do this with getmail I might have to use fetchmail instead.

**Comment by dotlambda** [comment]
The obvious solution for 1) is using Postfix's
```
sendmail -i user@example.org
```
I must have been blind.

I think I'll use `-f postmaster@example.org` so that I am notified whenever an email bounces.

**Comment by r-raymond** [comment]
I'm glad you found a solution that works for you. However, wouldn't it be easier
to simply tell google to forward your email? That's what I do with old hotmail
addresses, university addresses, etc.

**Comment by phdoerfler** [comment]
@dotlambda I'm hijacking this issue because I too am using `getmail` with NMS and it's almost working perfectly. The only thing missing is spam filtering. I was expecting this to work thanks to this carefully hand crafted config:

```
[destination]
type = MDA_external
path = /run/wrappers/bin/sendmail
arguments = ("-i", "-bm", "-r", "%(sender)", "myuser@example.com")
unixfrom = true
```

but `rspamd` doesn't see a reason to look at mail processed like this. Did you have any success with this?

**Comment by dotlambda** [comment]
No, I didn't set up spam filtering yet. I think https://github.com/vstakhov/rspamd/issues/520 might be of interest. But maybe the only way to achieve this is using something like procmail.
