### ISSUE TITLE
Catch-all aliases

### ISSUE THREAD

**Issue by yrashk** [r-raymond/nixos-mailserver#49]
Hi, first of all thanks for this great project. I already deployed it in small-scale production.

I was wondering if you have any plans for catch-all aliases/forwarders; or if I can, perhaps, contribute this?

**Comment by r-raymond** [comment]
Hi, awesome idea!

Contributions are very welcome! If you need any help implementing the feature, let me know; I'm not at home this weekend, but I can answer any questions on monday.

Did you run into any problems during deployment? Anything we could make smoother for the users?

Thanks for the initiative!

**Comment by eqyiel** [comment]
@yrashk this is already possible:

```nix
extraVirtualAliases = {
  "@maher.fyi" = "ruben@maher.fyi";
};
```

This way all mails to users that don't exist go to my inbox.

Unless I've misunderstood you?

**Comment by yrashk** [comment]
Just tested, worked perfectly. Thank you!

As for your original question -- so far I had no hiccups with your setup,
denting was smooth! Thank you for all the work you put into it.

**Comment by r-raymond** [comment]
I was not aware this was already possible :) (I'm not a big fan of catch all's) We should explicitly document this, or maybe add it to the domain list? Sth. like

```nix
domains = { "example.com" = { catchAll = "user1@example2.com" }
                    };
```

maybe?

**Comment by yrashk** [comment]
I like the idea of having a dedicated, explicit configuration option for
this.

**Comment by r-raymond** [comment]
Ok, I added a catchAll field to the userAccounts, i.e. you can now

```
loginAccounts = {
    "a@a.com" = {
         catchAll = [ "a.com" "b.com"];
    };
};
```

To make `a@a.com` a catch all for both `a.com` and `b.com`. I would recommend using this over the suggested solution, because otherwise the catchAll address also gets the right to send as every user og this domain.

**Comment by yrashk** [comment]
Awesome stuff! Thank you so much.

**Comment by eqyiel** [comment]
@r-raymond it looks like this option makes _all_ of the mail to the `catchAll` domain go to that user, regardless of whether it is addressed to an existing user.  Is that intentional?

I suspect it's because the virtual_alias_map only includes the catchAll address.

I'll see if I can come up with a test to show this...

**Comment by r-raymond** [comment]
Oops. I just assumed postfix does the sane thing here, I guess I was wrong. Thank you very much for keeping an eye out for that!
