### ISSUE TITLE
Notification when free space is low

### ISSUE THREAD

**Issue by phdoerfler** [r-raymond/nixos-mailserver#55]
Not sure how to tackle this the best, but I bet there are tools / services available that send an email to root@localhost when there is less than X GiB free space. I feel like this would make for a very nice addition to a mail server. Or this is a separate issue and should not be part of this repository. Thoughts?

**Comment by r-raymond** [comment]
Sounds like a cool plan. I think I would simply combine that with #35 to send a daily mail including the used space. I think it should send to the postmaster addresses instead of root@localhost. Maybe one should be able to specify a "maitenance address" where such logs get sent.

For the tool itself, I think a simple

```
df -h | sendmail postmaster@example.com
```

should do the trick.

**Comment by phdoerfler** [comment]
I don't know about others but at least I tend to overlook mails that are generated daily and contain more or less the same content each day.
I was more thinking along the lines of a "ALERT: only 200 MiB space remaining on /" that is hard to miss. Having no free space means being unable to receive any more mails from outside so this is something that then should be solved ASAP. Also: `nix-collect-garbage -d`.

**Comment by phdoerfler** [comment]
I went ahead and set up monix. I know it adds another moving part, but at least it doesn't open any ports to the outside world. And between "homebrew some funky bash script" and "use some existing lightweight tool" I think it is obvious what to choose.

I shall file this as a PR but we should introduce a config option for what mail address to send important things (like: disk space low, some cron job failed, etc) so I can replace "root@localhost" with something more specific. Or should this stuff just go to `postmaster`? This is a mail server after all.

**Comment by r-raymond** [comment]
Hmm, I agree monit looks tempting. Crazy world we live in where the bash "one-liner" gets replaced by the "small tool" that runs a http server.

Anyway, I think we can utilize monit for more than just disk usage in the future, so I feel ok to include it at this point
