### ISSUE TITLE
Any way to forward to non-local addresses?

### ISSUE THREAD

**Issue by telent** [r-raymond/nixos-mailserver#59]
I'm very much liking this batteries-included approach to mail service: thank you for writing and maintaining it.

I had a look at the docs and I skimmed the code though I can't claim I understand it well.  Is there anyway to create an alias that forwards email to a remote address?  For example, suppose SNM is serving my  vanity domain `bad.example.com` and I want mail for `nextdoor@bad.example.com` to be sent onto `j.smith@gmail.com`.  

I thought I could use extraVirtualAliases for this but it checks the recipient is a valid login account.  Which confuses me slightly because what does this do that adding an entry to `loginAccounts._name_.aliases` doesn't?

**Comment by telent** [comment]
Oh, I think I've answered my own question: use a sieveScript

```
   loginAccounts = {
        "gmail@example.net" = {
            hashedPassword = "whatevr";
           sieveScript = '' 
                redirect "somebody@gmail.com";
           ''; 
        };
        # ...
    }
```

**Comment by r-raymond** [comment]
Thanks for using SNM, I'm glad you figured out your problem. This should be documented however, maybe a wiki howto section?
