### ISSUE TITLE
Postfix won't send mail because of invalid SMTP banner

### ISSUE THREAD

**Issue by phdoerfler** [r-raymond/nixos-mailserver#6]
postfix complains about it in the logs when you try to connect on TCP port 587:

```
Sep 12 20:32:53 mail.example.com postfix/smtpd[4855]: fatal: open dictionary: expecting "type:name" form instead of "smtpd_tls_auth_only"
```

In fact, this keeps postfix from replying with its banner, thus preventing any client to send mail.

This goes away when correctly indenting the extra config. The "# Extra Config" part is indented differently than the rest. This keeps nixos from stripping the whitespace correctly thus the resulting postfix config is indented which postfix does not like.

**Comment by r-raymond** [comment]
Good catch!
