### ISSUE TITLE
README Question (B) Step 4

### ISSUE THREAD

**Issue by katyo** [r-raymond/nixos-mailserver#62]
At the section (B) [Step 4: Set SPF Records](https://github.com/r-raymond/nixos-mailserver#step-4-set-spf-records) in README the SPF record in table below have the type `TXT`, also testing command `dig` goes with `-t TXT` as argument.
It seems to be wrong but I don't sure.

**Comment by r-raymond** [comment]
This is actually correct. Should we revise the wording to make this more clear that it is indeed a `TXT` record?

**Comment by katyo** [comment]
Oh, it seems the SPF records actually deprecated.

**Comment by r-raymond** [comment]
Ok, I added a short note. Thanks for the feedback, and thanks for using SNM!
