### ISSUE TITLE
Remove clamav from systemPackages

### ISSUE THREAD

**Issue by katyo** [r-raymond/nixos-mailserver#64]
I don't need virus scanning feature, but as I see the `clamav` package will be installed anyway:
[environment.nix#L25](/r-raymond/nixos-mailserver/blob/master/mail-server/environment.nix#L25)

As you can see in clamav service [clamav.nix#L79](/NixOS/nixpkgs/blob/release-17.09/nixos/modules/services/security/clamav.nix#L79) youself because it will be installed when service enabled [clamav.nix#L23](/r-raymond/nixos-mailserver/blob/master/mail-server/clamav.nix#L23). So I suggest simply remove it from `systemPackages`.

**Comment by r-raymond** [comment]
Good catch, I'll fix it asap. Feel free to also send PR's for such things :)
