### ISSUE TITLE
Dovecot bug

### ISSUE THREAD

**Issue by r-raymond** [r-raymond/nixos-mailserver#67]
The newest version of dovecot fails with

```
server# [  233.257819] dovecot[1130]: imap-login: Error: Failed to initialize SSL server context: Couldn't parse DH parameters: error:0906D06C:PEM routines:PEM_read_bio:no start line: Expecting: DH PARAMETERS: user=<>, rip=192.168.1.1, lip=192.168.1.2, session=<Z2g4KkRkbsjAqAEB>
server# [  233.299718] dovecot[1130]: imap-login: Disconnected: TLS initialization failed. (no auth attempts in 0 secs): user=<>, rip=192.168.1.1, lip=192.168.1.2, session=<Z2g4KkRkbsjAqAEB>
```

compare to [archlinux forums](https://bbs.archlinux.org/viewtopic.php?id=233452)

**Comment by phdoerfler** [comment]
I'd make that configurable so the tests can use the bare minimum and a production server can use whatever the CPU can handle.

**Comment by phdoerfler** [comment]
Is there an ETA on this?

**Comment by r-raymond** [comment]
I pushed a test branch "dovecot23".

My problem is: If dovecot version is `< 2.3` then it does not know `ssl_dh`, if it is `>= 2.3` it requires it to be set (great policy from dovecot there). Unfortunately the tests on travis can only use nix (not nixos) and that tracks unstable. Hence it has dovecot `2.3`, whereas on Nixos it is dovecot `2.2....`. I fixed this with a `dovecot23` option which is beyond ugly of course. If anyone knows how to figure out what version of a package is being used from within the nix file, please let me know.

The travis test of this branch also have the problem that the VM sometimes times out when trying to connect, but that seems to be somewhat random and not related to the project.

**Comment by phdoerfler** [comment]
Thanks for the heads up!

Just in case you have not tried this yourself yet:
Is it possible to tell travis nix what version of nixpkgs it should use? That way it could use a version of nixpkgs which is closer to the stable channel. Or at least one using the same dovecot version as stable.

You might find these helpful:
- https://github.com/NixOS/nixpkgs/issues/9682
- https://gist.github.com/zimbatm/de5350245874361762b6a4dfe5366530

**Comment by eqyiel** [comment]
@phdoerfler it's possible, see here for an example: https://github.com/eqyiel/node-imapnotify/blob/9fe77ca3c836a67f573dc4bc7bb3c6deae381ddb/nix/run-tests.nix#L13

I'm pinning to the version of `nixpkgs` defined by this derivation: https://github.com/eqyiel/node-imapnotify/blob/9fe77ca3c836a67f573dc4bc7bb3c6deae381ddb/nix/nixos-unstable.nix

I will look into this tomorrow if no one else does it first.

**Comment by eqyiel** [comment]
@r-raymond see https://github.com/r-raymond/nixos-mailserver/pull/76

Thanks for considering that package, I'll tell you more about it if I ever get around to finishing it!

**Comment by eqyiel** [comment]
@phdoerfler this is fixed on current master!

**Comment by phdoerfler** [comment]
@eqyiel I'm sorry - what is fixed and where?

**Comment by eqyiel** [comment]
@phdoerfler the dovecot configuration should now build on both stable and unstable channels 😅
