### ISSUE TITLE
unbound requires ipv6

### ISSUE THREAD

**Issue by nico202** [r-raymond/nixos-mailserver#68]
Hi, I upgraded the config and during the switch unbound failed to bind to ::1. I have (had) enableIPv6 = false, setting it to true does work, but maybe it should default to the ipv4 analogous if ipv6 is disabled, or assert ipv6 is enabled and fail loudly if it isn't

Nicolò

**Comment by r-raymond** [comment]
Hi, sry that slipped through the cracks. We could modify `services.unbound.interfaces`, or introduce an `ipv6` switch in the config. There is also a competing PR right now that uses `kresd` instead of  `unbound`.  Could you check if this is a problem with `kresd` too?

Thanks for using SNM!

**Comment by nico202** [comment]
Thank *you* for writing it!
I'll test it this evening since I'm away from my server right now and I don't feel comfortable changing network settings remotely (I have once been cut out and I don't want to repeat it), but I'll have physical access to it later today :)

**Comment by nico202** [comment]
Yes, I can confirm that kresd works even with ipv4-only.
