### ISSUE TITLE
[advice] Radicale config

### ISSUE THREAD

**Issue by dotlambda** [r-raymond/nixos-mailserver#72]
This is more like an issue to help people who want to have their own CalDAV server and already have nixos-mailserver running. I have configured a [Radicale](http://radicale.org/) server to use the same users as nixos-mailserver:
```nix
{ config, pkgs, lib, ... }:

with lib;

let
  mailAccounts = config.mailserver.loginAccounts;
  htpasswd = pkgs.writeText "radicale.users" (concatStrings
    (flip mapAttrsToList mailAccounts (mail: user:
      mail + ":" + user.hashedPassword + "\n"
    ))
  );

in {
  services.radicale = {
    enable = true;
    config = ''
      [auth]
      type = htpasswd
      htpasswd_filename = ${htpasswd}
      htpasswd_encryption = crypt
    '';
  };

  services.nginx = {
    enable = true;
    virtualHosts = {
      "cal.example.com" = {
        forceSSL = true;
        enableACME = true;
        locations."/" = {
          proxyPass = "http://localhost:5232/";
          extraConfig = ''
            proxy_set_header  X-Script-Name /;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_pass_header Authorization;
          '';
        };
      };
    };
  };

  networking.firewall.allowedTCPPorts = [ 80 443 ];
}
```

**Comment by r-raymond** [comment]
Awesome!

So... should we integrate this into SNM?

**Comment by dotlambda** [comment]
I'm not sure. It's a *mailserver* after all.

**Comment by r-raymond** [comment]
Let's leave this issue open so people can express their opinions.

I vote for yes, I think ideally SNM will also provide calendar and contact synchronization.

**Comment by nico202** [comment]
I'd say yes because it's useful, but no as @dotlambda. Maybe if we collect some of those in an "extra" package? Ideally creating a small *nixos-server* ecosystem in the future

**Comment by nico202** [comment]
I'd say yes because it's useful, but no as @dotlambda. Maybe if we collect some of those in an "extra" package? Ideally creating a small *nixos-server* ecosystem in the future

**Comment by phdoerfler** [comment]
Oh this is cool! As someone guilty of adding things to this project that - though helpful - not strictly required for operating a mailserver (hello monit) I say let's keep it!
But I do side with @dotlambda in that this is indeed a *mailserver*.
I therefore vote for adding it (extra package or not) and having it disabled by default.

**Comment by r-raymond** [comment]
If we go the extra package way, does anyone have a good idea on how to manage that? Should we collect a list of github repos that are pulled if a boolean is set?

**Comment by r-raymond** [comment]
I've copied the @dotlambda 's config to a wiki page. Feel free to add comments, or tweak the config.
