### ISSUE TITLE
v2.1 Release

### ISSUE THREAD

**Issue by r-raymond** [r-raymond/nixos-mailserver#75]
I've added a release candidate for v2.1 six weeks ago, and there are no open bugs that I'm aware of right now that would prevent from releasing this as stable. If you have any concerns, let me know, otherwise I'll prepare a release this weekend.

**Comment by jbboehr** [comment]
I've been using one of the RCs for a while now and it's been working fine.

**Comment by r-raymond** [comment]
As a quick update, I'm still fixing an error with travis ci before releasing the new version
