### ISSUE TITLE
Thunderbird complains about username / password

### ISSUE THREAD

**Issue by sjau** [r-raymond/nixos-mailserver#80]
I wanted to test this but Thundebird just keeps complaining:

"Configuration could not be verified - is the username or password wrong?"

I tried to use the full email as username and also just the left-hand side of the @. Also I tried a long password and a short simple one. I just couldn't login

IMP Port 143, STARTTLS, Normal Password
SMTP Port 587, STARTTLS, Normal Password

**Comment by nico202** [comment]
Thunderbird, same imap port, smtp port 25, starttls, normal password, working.

Have you registered MX and so on?

**Comment by phdoerfler** [comment]
I am successfully using this mailserver with thunderbird on Windows. No problems there.

**Comment by sjau** [comment]
no, not registered as mx as I provide the domain directly for the server

**Comment by nico202** [comment]
Yeah thinking about it should not be needed

**Comment by sjau** [comment]
I also opened the ports on the firewall and I had to disable "enableManageSieve" as nixos complained when it was enabled.

**Comment by sjau** [comment]
So, for login: Do use use the full email address or just the left-hand side of the @, e.g.
`user` or `user@home.domain.tld` ?

For the password hashing, do I use
`mkpasswd -m sha-512 "password"` or `mkpasswd -m sha-512 password`

**Comment by nico202** [comment]
```mkpasswd -m sha-512``` and insert the password at the prompt. user@domain.tld

**Comment by nico202** [comment]
does telnet works?

**Comment by phdoerfler** [comment]
you can test encrypted IMAP using openssl:
`openssl s_client -quiet -host mail.example.com -port 143 -starttls imap`.
This will start an interactive session where you can communicate with your IMAP server:

```
. login user@example.com yourPassword
. namespace
. list "" *
. select "INBOX"
. search body „needle“
. search subject Testmail
. UID SEARCH ALL
. FETCH 1 BODY[]
. fetch 13 body[header]
. logout

**Comment by sjau** [comment]
No, that doesn't work:

```
openssl s_client -quiet -host localhost -port 143 -starttls imap
140237477145344:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:
```

**Comment by r-raymond** [comment]
Hi sjau, thanks for using SNM and sorry for the inconvenience.

Are you on stable (17.09) or unstable? What is in the journalctl when trying to log in like above?

**Comment by r-raymond** [comment]
then I'm assuming it is either

1) You don't use master but an older version of SNM (there was an SSL bug that got fixed just yesterday with Dovecot 2.3)
2) You need to wait longer until the DH file is created (look at the paramter for dh-file). 2048 can take multiple minutes to create on a low entropy machine.

**Comment by sjau** [comment]
Using 2.0.4 like it says here

**Comment by r-raymond** [comment]
I'll release a new version later today that contains the necessary fix.

**Comment by sjau** [comment]
Where would the DH file be?

**Comment by r-raymond** [comment]
`2.0.4` (and also `2.1`) only work on Nixos stable. If you want unstable, you have to use the master branch (it needs a commit from yesterday). Or wait until I release new version today. the dh file only gets created if you have dovecot23 (which you have) and are tracking master (so not for you). It is located in the certificate directory.

**Comment by sjau** [comment]
How to use master?

**Comment by r-raymond** [comment]
replace `v2.0.4` with `master`

**Comment by sjau** [comment]
well, was confused because github only shows zip for download.... yeah, now it seems to work. Let me switch back again to LE ECC certs that I got through dns-01

**Comment by sjau** [comment]
yes, it works :)

**Comment by sjau** [comment]
Also, using master now, it doesn't complain about `enableManageSieve = true;` anymore

Next thing, setting up a webserver with roundcube.

**Comment by r-raymond** [comment]
great!

**Comment by r-raymond** [comment]
Btw. for roundcube you probably need some type of sql server which this project tried to avoid at all costs. So it might not integrate too well with SNM

**Comment by sjau** [comment]
what other nice webmail is there besides roundcube that doesn't require database?

**Comment by r-raymond** [comment]
Depends on your definition of nice, but I think squirrle mail doesn't need one. If you find some other great solutions, let us know :)

**Comment by sjau** [comment]
Roundcube can use sqlite though

**Comment by r-raymond** [comment]
well give it a shot. I don't know how one communicates the login accounts. Maybe it simply uses IMAP and caches the results. I don't know, since I don't use webmail.

**Comment by sjau** [comment]
Will do so.... one more question:

What is the difference between the aliases and the extarVirtualAliases?

**Comment by r-raymond** [comment]
nothing, extraVirtualAliases is just if you feel like it is more comfortable to add aliases outside of the user declarations. E.g. if you have postmaster, abuse etc. of multiple domains forwarded it might be more convenient to do that in extraVirtualAliases.

**Comment by sjau** [comment]
So, got it setup. It wasn't too hard:

```
    services.nginx = {
        enable = true;
        virtualHosts."server.domain.tld" = {
            forceSSL = true;
            root = "/var/www/roundcube";
            locations."/".index = "index.php index.html index.htm";
            locations."~ \.php$".extraConfig = ''
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
            '';
            sslCertificate = "/home/hyper/Syncthing/https-cert.pem";
            sslCertificateKey = "/home/hyper/Syncthing/https-key.pem";
        };
    };
    services.phpfpm.poolConfigs.mypool = ''
        listen = 127.0.0.1:9000
        user = nobody
        pm = dynamic
        pm.max_children = 5
        pm.start_servers = 2 
        pm.min_spare_servers = 1 
        pm.max_spare_servers = 3
        pm.max_requests = 500
    '';
```

Downloaded the full roundcube tgz, extracted it, set according permissions for nginx so he can create db and stuff...

Few things like mimetypes would still need to be handled. I just want to use it as local server for rss2email :) On my other servers I do already way too much spam cleaning etc... but here I just let everything pass.

**Comment by phdoerfler** [comment]
@sjau that's neat! Can I inconvenience you to submit this as a PR?

**Comment by r-raymond** [comment]
Awesome. If that is something people want, we could add this as an option.

**Comment by phdoerfler** [comment]
I do occasionally. For instance right now I am converting my old mail from locally stored Apple Mail files to maildir to put it on the mail server. To check and see if the conversion went OK (like folder names and such) a dumb webmail client would be great. Desktop mail clients tend to be "smart" and cache things and when you empty your whole maildir and then put thousands of converted messages in it you want something dumb that doesn't get confused over some thousand messages that are no longer there. But that's just me.

**Comment by sjau** [comment]
not really sure how to make a PR out of it.... the above just sets the environment in such a way that RC can be downloaded and used... but maybe provide a full RC installation

**Comment by sjau** [comment]
Still gnawing my teeth out to get sieve to properly work in roundcube...

I can telnet just fine and get proper answer - so dovecot is doing it fine - but I can't just get it to run in rc :(

Anyway, I think this can be closed? Issue was - as most of the time - PEBKAC :)

**Comment by r-raymond** [comment]
Take a look at the `enableManageSieve` option which allows changing sieve scripts via imap. Feel free to close the issue if you think your problem is resolved.

**Comment by sjau** [comment]
As I said, your script set it up correctly:

```
telnet 10.0.0.10 4190
Trying 10.0.0.10...
Connected to 10.0.0.10.
Escape character is '^]'.
"IMPLEMENTATION" "Dovecot Pigeonhole"
"SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext"
"NOTIFY" "mailto"
"SASL" ""
"STARTTLS"
"VERSION" "1.0"
OK "Dovecot ready."
```

It's just that I get errors with roundcube... it should work but haven't figured it out yet....
