### ISSUE TITLE
2.1.1 fails to activate when cert directory is missing

### ISSUE THREAD

**Issue by The-M1k3y** [r-raymond/nixos-mailserver#88]
I just switched from 2.0.4 to 2.1.1 and found that postfix and dovecot won't start due to the missing dh.pm file. The file is not generated, when the target directory does not exist. When the directory is created manually, it works.

**Comment by The-M1k3y** [comment]
Additional Info: I'm providing the certs by file path, since I already have a nginx running, so no cert directory gets created.

**Comment by r-raymond** [comment]
Sorry about the inconvenience. I assumed the cert directory would exist when creating the file. I'll fix asap.

**Comment by The-M1k3y** [comment]
No problem. I'm glad I finally have a tool for a mailserver without a lot of headache. Your doing an awesome job here.
